# Generated by Django 3.1.3 on 2020-11-28 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacjasali',
            name='status',
            field=models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 19, 45, 39, 731941)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 19, 45, 39, 729941)),
        ),
    ]
