# Generated by Django 3.1.3 on 2020-11-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
            field=models.CharField(choices=[('S', 'Sala'), ('L', 'Laboratorium'), ('P', 'Pracownia')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 11, 46, 44, 323253)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 11, 46, 44, 321253)),
        ),
    ]
