# Generated by Django 3.1.3 on 2020-12-03 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201129_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacjapokoju',
            name='status',
            field=models.CharField(choices=[('Z', 'Zaakceptowana'), ('O', 'Odrzucona'), ('R', 'W trakcie rozpatrywania')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='pomieszczenie',
            name='rodzaj_pom',
            field=models.CharField(choices=[('S', 'Sala'), ('L', 'Laboratorium'), ('P', 'Pracownia'), ('A', 'Aula wykladowa')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='rezerwacjapokoju',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 19, 35, 13, 537628)),
        ),
        migrations.AlterField(
            model_name='rezerwacjasali',
            name='data_wykonania_rezerwacji',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 19, 35, 13, 535484)),
        ),
    ]
